### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [MrPibol/tfp-splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by MrPibol** [comment]
Thank you, Mike.
While it made the page responsive to mobile devices, it didn't fixed the issue I have with the footer: the columns don't stack up for mobile users.
JP

**Comment by Mikeysax** [comment]
Nice job adding that :+1: 

As for the footer, I recommend going over debugging CSS with google dev tools with your mentor.
